services:
  - type: web
    name: vitara
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        value: enter your own key
